services:
  tradenote:
    build:
      context: .
      dockerfile: Dockerfile
    # optional: name the built image so itâ€™s cached/tagged
    image: tradenote-local:latest
    container_name: tradenote_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://tradenote:tradenote@mongo:27017/tradenote?authSource=admin
      TRADENOTE_DATABASE: tradenote
      APP_ID: 123456
      MASTER_KEY: 123456
      TRADENOTE_PORT: 8080
    networks:
      - tradenote_net
  mongo:
    image: mongo:latest
    container_name: tradenote_db
    restart: unless-stopped
    volumes:
      - tradenote_db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: tradenote
      MONGO_INITDB_ROOT_PASSWORD: tradenote
      MONGO_INITDB_DATABASE: tradenote
    networks:
      - tradenote_net
networks:
  tradenote_net:
    driver: bridge

volumes:
  tradenote_db:
    name: tradenote_db